### ISSUE TITLE
Use updated signature files

### ISSUE THREAD

**Issue by anjackson** [ukwa/siegfried-js#1]
Rather than relying solely on built-in sig files, we can use the official Siegfried update server. This now includes WikiData. 

e.g. https://www.itforarchivists.com/siegfried/update/wikidata 

The other ones are listed at https://github.com/richardlehane/siegfried/wiki/Getting-started#non-pronom-signatures

**Comment by anjackson** [comment]
Ah, won't work without modification to the update server... 

```
Access to fetch at 'https://www.itforarchivists.com/siegfried/latest/wikidata' from origin 'https://siegfried-js.glitch.me' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by richardlehane** [comment]
I'll have a go at adding this shortly

**Comment by richardlehane** [comment]
CORS headers are now in place for those paths

**Comment by anjackson** [comment]
Perfect, thank you! That works great now.
